language: android
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.android/build-cache
android:
  components:
  - build-tools-22.0.1
  - extra-android-m2repository
  - extra-google-m2repository
before_install:
- gradle dependencies || true
script:
- ./travis-build.sh
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
env:
  matrix:
    secure: QmnrvK/Zm29dKzAARaig4NPds/dGjTkoo32NAc0JDwYxZ/IGBtW6JdG4ZnISzQ8OwaA1ONdZgJK4uAFGMfEtSyXm2gFyTW/pIRZZfS+4ESNtvBMglR5Ls3fcN0NkS37fCH7oxLV4gxWWOtyWrVQt0B4GQp/4HCWHKNFAhyCOvhaSGKqXLP0RcSFd1Zk0HnOW1xumiH2crDu8EQab48nsfXb+BY3ywtuqglqhimI4aK4g9GvDRfEZCUKdWDG9gX3g0OwKcWE+x1otC89fQghEBKdgqNl3Qy07Tp9qWiDoVj80sC9oxerY+53swP74wNM/yqBf7nQXWSUMdMr14TJr7OyGGLFA8JDibJADz1uBNaKvnX7RZGbMGJfy1cRLOk3o28wEyoA5LaxSURk9ozdzL1sCj9/2/gxbNYrssKXx/OnZGwuLZZp4V4Y/Ya2wHc+6J0N8z2CBUP+oXhHTUDDRkZ0Gr0Mtg3oAGdaoAzf4lUq3KF9eJorLF1p6frQoKyc+q/ZGBVaEAR5L8IVgxlxKtYNPmjzagxcYgXw/ai6AyBguRk8o7UF4tZaYTqYMi11TzdEYTIPFtmyO1vbCFHavsq3nEbPfWFMjJCMLoUaU8RdWpQ+Xk06hvXBJfzCJPtIUIfQZdezIJrUK8JBFWGd6EQInXZ+sllOPf6fuP65UcPo=
